services:
  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    environment:
      ASPIRE_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"
      ASPIRE_DASHBOARD_OTLP_HTTP_ENDPOINT_URL: "http://[::]:18890"
    ports:
      - "18888:18888" # Dashboard UI
      - "18889:18889" # OTLP gRPC receiver
      - "18890:18890" # OTLP http receiver
