<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(NetCoreAppVersion)</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharpSense.Domain\SharpSense.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentResults" />
    <PackageReference Include="JetBrains.Annotations" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="SerilogTimings" />
  </ItemGroup>

</Project>
