<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(NetCoreAppVersion)</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Abstractions.TestingHelpers" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SharpSense.Infrastructure\SharpSense.Infrastructure.csproj" />
    <ProjectReference Include="..\SharpSense.Testkit\SharpSense.Testkit.csproj" />
  </ItemGroup>

</Project>
