// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SharpSense.Infrastructure.Persistence;

#nullable disable

namespace SharpSense.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SharpSenseDbContext))]
    [Migration("20260419003423_AddCodeNodeSourceSpan")]
    partial class AddCodeNodeSourceSpan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("SharpSense.Domain.KnowledgeGraph.Edges.DependencyEdge", b =>
                {
                    b.Property<string>("CallerId")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("CalleeId")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("EdgeType")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("CallerId", "CalleeId", "EdgeType");

                    b.HasIndex("CalleeId");

                    b.HasIndex("CallerId");

                    b.ToTable("DependencyEdges", (string)null);
                });

            modelBuilder.Entity("SharpSense.Domain.KnowledgeGraph.Nodes.CodeNode", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("EndLine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullyQualifiedName")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativeFilePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("StartLine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("VectorEmbedding")
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("FullyQualifiedName");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RelativeFilePath");

                    b.ToTable("CodeNodes", (string)null);
                });

            modelBuilder.Entity("SharpSense.Domain.KnowledgeGraph.Nodes.ProjectNode", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativeFilePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RelativeFilePath")
                        .IsUnique();

                    b.ToTable("ProjectNodes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
