name: Release SharpSense

on:
  workflow_dispatch:

jobs:
  build-test-publish:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      - name: Build
        run: dotnet build ./src/SharpSense.Cli/SharpSense.Cli.csproj -c Release

      - name: Test
        run: dotnet test -c Release

      - name: Calculate Semantic Version
        id: versioning
        uses: paulhatch/semantic-version@v5.4.0
        with:
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          version_format: "${major}.${minor}.${patch}"
          bump_each_commit: false

      - name: Pack NuGet Tool
        run: >
          dotnet pack ./src/SharpSense.Cli/SharpSense.Cli.csproj
          -c Release
          /p:PackageVersion=${{ steps.versioning.outputs.version }}
          -o ./artifacts

      - name: Publish to NuGet.org
        run: >
          dotnet nuget push ./artifacts/*.nupkg
          --api-key ${{ secrets.NUGET_API_KEY }}
          --source https://api.nuget.org/v3/index.json
          --skip-duplicate

      - name: Create GitHub Release and Tag
        uses: softprops/action-gh-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.versioning.outputs.version_tag }}
          name: Release ${{ steps.versioning.outputs.version_tag }}
          generate_release_notes: true
